version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
      - ../secrets/ssl:/etc/nginx/ssl
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mariadb

networks:
  inception:
    name: inception

